apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vector-poc

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: vector-config
    files:
      - vector.yaml=configs/vector.yaml
    options:
      labels:
        app: vector-poc-backend
        component: vector

secretGenerator:
  - name: postgres-credentials
    literals:
      - POSTGRES_HOST=postgres.vector-poc.svc.cluster.local
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=logs
      - POSTGRES_TABLE=application_logs
      - POSTGRES_USER=vector_user
      - POSTGRES_PASSWORD=vector_user
    options:
      labels:
        app: vector-poc-backend
        component: database