apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vector-poc

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: postgres-init-script
    files:
      - init.sql=configs/init.sql
    options:
      labels:
        app: postgres
        component: database

secretGenerator:
  - name: postgres-credentials
    literals:
      - POSTGRES_DB=logs
      - POSTGRES_USER=vector_user
      - POSTGRES_PASSWORD=vector_user
    options:
      labels:
        app: postgres
        component: database